import Head from 'next/head'
import styles from '../styles/Home.module.css'
import '../styles/globals.css'

function MyApp({ Component, pageProps }) {
  return (
  <div>
    <Head>
      <title>Castles And Critters </title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className={styles.main}>
      <Component {...pageProps} />
    </main>
    <footer className={styles.footer}>
    </footer>
  </div>
  )
}

export default MyApp
