import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { abilities } from '../data/abilities'

export default function Home({abilities}) {
  console.log(abilities);
  //console.log(JSON.parse(JSON.stringify(abilities)));

  const abilityDivs = abilities.map(ability => 
    <div>{ability.name}</div>
  );

  console.log(abilityDivs);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

      {abilityDivs}
        
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}

export async function getStaticProps() {
  return {
    props: {
      abilities: abilities
    }
  }
}
